// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using day09LabCodeFirst.Models;

#nullable disable

namespace day09LabCodeFirst.Migrations
{
    [DbContext(typeof(Day09LabCFContext))]
    [Migration("20251017011623_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("day09LabCodeFirst.Models.LttLoaiSanPham", b =>
                {
                    b.Property<int>("lttId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("lttId"));

                    b.Property<string>("lttMaLoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("lttTenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("lttTrangThai")
                        .HasColumnType("bit");

                    b.HasKey("lttId");

                    b.ToTable("LttLoaiSanPham");
                });

            modelBuilder.Entity("day09LabCodeFirst.Models.LttSanPham", b =>
                {
                    b.Property<long>("lttId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("lttId"));

                    b.Property<int>("LttLoaiSanPhamlttId")
                        .HasColumnType("int");

                    b.Property<decimal>("lttGiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("lttHinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("lttMaLoai")
                        .HasColumnType("bigint");

                    b.Property<string>("lttMaSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("lttSoLuong")
                        .HasColumnType("int");

                    b.Property<string>("lttTenSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("lttTrangThai")
                        .HasColumnType("bit");

                    b.HasKey("lttId");

                    b.HasIndex("LttLoaiSanPhamlttId");

                    b.ToTable("LttSanPham");
                });

            modelBuilder.Entity("day09LabCodeFirst.Models.LttSanPham", b =>
                {
                    b.HasOne("day09LabCodeFirst.Models.LttLoaiSanPham", "LttLoaiSanPham")
                        .WithMany("LttSanPhams")
                        .HasForeignKey("LttLoaiSanPhamlttId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LttLoaiSanPham");
                });

            modelBuilder.Entity("day09LabCodeFirst.Models.LttLoaiSanPham", b =>
                {
                    b.Navigation("LttSanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
